### ISSUE TITLE
Temperature compensated RTC

### ISSUE THREAD

**Issue by hp1337** [xorbit/LiFePO4wered-Pi#26]
Hi there, just got my LiFePO4wered/Pi+. Looks amazing and is working great so far.

I was wondering if you are planning on supporting a temperature compensated RTC. I live in Canada and am planning on using it outdoors. This means there are wide fluctuations in temperature which can affect clock accuracy. I know of a whitepaper from TI that demonstrates how to make an RTC that is extremely accurate across a wide temperature range using the ADC, and Timer_A in an MSP430:

http://www.ti.com/lit/ml/slap107/slap107.pdf

If there is no plan for this, is there any plan to release the firmware so that it can be modified to add features? I realize that may be a challenging request however. Is it even possible to flash the MSP430 once it has been shipped to the customer?

Thanks again!

**Comment by xorbit** [comment]
Hi,

Thanks for the suggestion!  I don't have any plans to implement this at the moment I'm afraid.  The problem is not so much the implementation in software as it is the infrastructure and time needed to implement the factory calibration.  I just don't have the bandwidth to work on this right now.

The firmware is also not open at the moment to keep copycats at bay and ensure I get a return on my investment.  This may change in the future though.  It is possible to reflash the MSP430 with your own firmware if you're inclined to develop your own though.

I would suggest that your application may be better served by adding a separate temperature compensated RTC module.  The RTC on the LiFePO4wered/Pi+ is intended as a poor man's RTC that is "good enough" for most people.  It was designed to transparently work with other time sources that may provide more accurate time, such as dedicated RTC modules, GPS modules, network time, etc.
