### ISSUE TITLE
Connecting a 12 V PSU to the VIN pads

### ISSUE THREAD

**Issue by daghemo** [xorbit/LiFePO4wered-Pi#30]
Since the LiFePO4wered/Pi+ can be powered from a wide input voltage range of 5V to 20V, I've soldered a 2-pin terminal block on VIN and hooked up a 12 V power supply.
Unfortunately just doing this seems to have broken my LiFePO4wered/Pi+. 
And I've tried twice with the same results.

I know that the VIN pads are supposed to be directly connected to the micro USB connector pins, but trying to put 12 V from the same power supply directly through the micro USB connector seems to work perfectly.

**Comment by xorbit** [comment]
This repo is about the host software tools, hardware related questions can be asked (as you did) at support@lifepo4wered.com.  Double posting here only wastes my time because now I have to also answer publicly in addition to helping you through your hardware specific problem.

Yes, the VIN pads and USB input are electrically connected, see the publicly available schematic on hackaday.io: https://cdn.hackaday.io/files/20909894570656/LiFePO4wered-PiPlus-5.pdf
I don't know why it would work differently in your tests.  I'll try to help you figure it out over email.
