### ISSUE TITLE
Needs 3A

### ISSUE THREAD

**Issue by worikgh** [xorbit/LiFePO4wered-Pi#54]
This is the solution I have been looking for, but Raspberry Pi 4 needs 3A.

Any plans to beef up output?

**Comment by xorbit** [comment]
The Raspberry Pi 4 is specified to need a 3A wall wart power supply, it does not actually need 3A to run.  Many people are using the LiFePO4wered/Pi+ with a Pi 4 successfully.  Most customers do not see output currents much more than 1.3A.

There are three reasons the foundation says you need a 3A power supply for the Pi 4:

- There are many poor power supplies on the market that don't meet their advertised power output.  By saying you need 3A, you may hopefully get a solid 2A.
- There are many bad cables on the market using thin gauge wire.  The Pi 4 is also lacking in on-board decoupling capacitance to supply short power spikes.  This means that as the Pi 4 pulls high current, the wire resistance causes a voltage drops, and you get undervoltage warnings and instability.
- They need to make sure to allocate the 1.2A maximum power for the USB output, even if you don't actually use it.

The LiFePO4wered/Pi+ solves the first two issues by actually being able to supply the advertised current, continuously.  And by being mounted right on the Pi, taking cable losses out of the equation.  I have never seen an undervoltage warning on a Pi powered by a LiFePO4wered/Pi+.

It is conceivable that if you add a lot of stuff like an LCD screen and USB HDD, you might have too much load for the LiFePO4wered/Pi+ to handle.  But I have not seen it happen and I have not heard any customers complain about it.  Especially since the latest revision 7, which can actually handle 2.5A continuous output on all units I've tested, although I don't advertise that yet.

To go to 3A output, the currents from a single LiFePO4 cell become too high to work reliably with a battery holder.  I'm working on next gen technology to take care of higher output, but currently 2.5A is the limit for rev 7.
