### ISSUE TITLE
Upgrade request: 2A or more

### ISSUE THREAD

**Issue by hblanken** [xorbit/LiFePO4wered-Pi#9]
I have recently received my LiFe and I really like it! Well done, impressive. I am using my Pi3 with 2 USB devices (one a 2nd Wifi, the other a gphoto2 image/video transfer) and a raspicam and 4 cores running quite a bit. I have tested a few UPS HATs now and one request I have is whether LiFe could pump out 2A or more, ideally 2.4A at peak. Is this possible?

**Comment by xorbit** [comment]
I'm working toward that goal.  The current hardware is not able to do it because of thermal limitations.  The PCB is just too small to provide much heat sinking.  Active cooling might increase how much power you can draw, but that's not ideal.

I have a new project on Hackaday.io, the goal is to be able to provide 2A continuously and more peak (current limit is set at 2.9A).  It has a bigger PCB, larger, higher current rated components and a new boost converter.  Check it out here: https://hackaday.io/project/20909-lifepo4weredpi.
